# sys._current_exceptions()